defaults: &defaults
  adapter: mysql

development:
  database: secpla
  username: root
  password: ""
  <<: *defaults

  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  postgres
  #     database: sample_development
  #     username: the_user
  #     password: secrets
  #     host:     localhost
  #   repo2:
  #     ...

test:
  database: db/secpla_test.db
  <<: *defaults
production:
  database: db/secpla_production.db
  <<: *defaults
